//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLayers2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Door
    {
        public int Id { get; set; }
        public string DoorNo { get; set; }
        public int StreetId { get; set; }
        public string Coordinates { get; set; }
    }
}
